version: "3"

services:
    ngnix:
        build: ./images/nginx
        ports:
            - 7501:80
        volumes:
            - /vagrant/www:/var/www
            - /vagrant/nginx/logs:/var/log/nginx
            depends_on:
                - php
mysql:
    image: mariadb:latest
    ports:
        - 3306:3306
    enviromment:
        MYSQL_ROOT_PASSWORD: qwerty
php:
    build: ./images/php
    depends_on:
        - mysql
    volumes:
        - /vagrant/www:/var/www:rw